---

xml_namespace: http://www.w3.org/XML/1998/namespace

languages:
  it: italian
  de: german
  la: latin
  fr: french
  gr: greek

fmt_names:

  emph:
    - emph
    - italic
    - underscore
    - underline

  single:
    - single

  double:
    - double

  superscript:
    - super
    - upper

  smcp:
    - smcp

workdir: working_directory

resource_classifications:
  
  hidden:
    - references
    - indexstyle

  parsepath:
    - personlist

  before_text:
    - preamble
    - after_preamble
    - after_text_start

  after_text:
    - after_text_end

resources:

  personlist:
    name: personlist.xml
    required: true
    output: path

  references:
    name: references.bib
    required: true

  preamble:
    name: latex_preamble.tex
    required: true
    output: read

  after_preamble:
    name: after_preamble.tex
    required: false
    output: read
    subst: \begin{document}

  after_text_start:
    name: after_text_start.tex
    required: false
    output: read
    subst: |
        \frontmatter
        \tableofcontents
        %s
        \mainmatter
        \setcounter{tocdepth}{0}
        \setsecheadstyle{\normalsize\bfseries}
        \setsubsecheadstyle{\normalsize\bfseries}
        \setsecnumdepth{none}
        \beginnumbering
    sub_include:
      name: introduction.tex
      subst: ''
      required: false

  after_text_end:
    name: after_text_end.tex
    required: false
    output: read
    subst: |
          \endnumbering
          \backmatter
          %s
          \printbibliography
          \printindex
          \end{document}
    sub_include:
      name: appendices.tex
      subst: ''
      required: false

  indexstyle:
    name: false
    ext: .mst
    required: false
    subst: |
        headings_flag 1
        heading_prefix "{\\bfseries "
        heading_suffix "}\\nopagebreak\n"
    output: path


caller_command: latexmk -g -cd -pdf -bibtex

string_replacements:
  - ['Horowhenua', 'Horo\-whenua']
  - ['Trémouille', 'Tré\-mouille']
  - ['HQ. C.O.', 'HQ.~C.O.']
  - ['C.O. Battalion', 'C.O.~Battalion']

regex_replacements:
  - ['\ +', ' ']
  - ['\n\ +', '\n']
  - ['\n\n+', '\n\n']
  - ['([A-Z.]{2,})\.\ (?=[A-Z])', '\1\@. ']

parser_options:
  ns_clean: true
  remove_comments: true
  remove_blank_text: true
...